"""initial_migrate

Revision ID: 7ddbd2d515a7
Revises: 
Create Date: 2025-03-18 13:41:39.638964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddbd2d515a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('brand', sa.String(length=250), nullable=True),
    sa.Column('vehicle_type', sa.String(length=250), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('engine_rating', sa.String(length=250), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(length=250), nullable=True),
    sa.Column('transmission', sa.String(length=250), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('drive_type', sa.String(length=250), nullable=True),
    sa.Column('extras', sa.String(length=250), nullable=True),
    sa.Column('folder_name', sa.String(length=250), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.Column('availability', sa.String(length=250), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_catalogue')
    # ### end Alembic commands ###
