"""Initial Migration

Revision ID: a052207c9b14
Revises: 
Create Date: 2025-03-20 05:29:59.625153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a052207c9b14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('brand', sa.String(length=250), nullable=True),
    sa.Column('vehicle_type', sa.String(length=250), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('engine_rating', sa.String(length=250), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(length=250), nullable=True),
    sa.Column('transmission', sa.String(length=250), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('drive_type', sa.String(length=250), nullable=True),
    sa.Column('extras', sa.String(length=250), nullable=True),
    sa.Column('folder_name', sa.String(length=250), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.Column('availability', sa.String(length=250), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('edits', sa.Integer(), nullable=True),
    sa.Column('posts_made', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('car_catalogue')
    # ### end Alembic commands ###
